collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/images"
    values:
      image: true

url: https://blog.atlastseason.art

plugins:
  - jekyll-feed
  - jekyll-seo-tag
