collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/images"
    values:
      image: true

domain: atlastseason.github.io
url: https://atlastseason.github.io/blog-atlast-test
